course_creation/config/routes.rb
CourseCreation::Engine.routes.draw do
  resources :certificates, except: [:show]
  resources :versions do
    member do
      put :publish
      get :preview
      get :syllabus, action: :show, version_view: 'Syllabus'
    end
    resources :course_sections, except: [:index, :show] do
      resources :resources do
        put :update_details
      end
      resources :videos, controller: 'resources', type: 'Video' do
        get :content, on: :new, action: :new, content: true
      end
      resources :presentations do
        resources :slides do
          member do
            put :update_settings
            put :update_ppt_title
            put :delete_bg_img
            put :update_title
            put :update_contents
            delete :destroy_column
            post :slide_clone
            put :apply_seetings
          end
        end
      end
      resources :section_assessments, controller: :assessments, type: 'section', only: [:new]
      resources :assessments
      resources :custom_contents
      resources :documents, controller: 'resources', type: 'Document' do
        get :content, on: :new, action: :new, content: true
      end
      resources :interactive_slides do
        resources :interactive_slides_informations do
          member do
            put :delete_slide_image
          end
        end
        resources :text_slides, controller:
          'interactive_slides_informations', type: 'TextSlide'
        resources :image_slides, controller:
          'interactive_slides_informations', type: 'ImageSlide'
        resources :text_image_slides, controller:
          'interactive_slides_informations', type: 'TextImageSlide'
      end
    end
    resources :evaluation_questions, except: [:show, :new]
    resources :resources
    get :documents, controller: 'resources', action: :index, type: 'Document'
    get :videos, controller: 'resources', action: :index, type: 'Video'
    resources :quotes, controller: 'resources', type: 'Quote'
    resources :notes, controller: 'resources', type: 'Note'
  end
  resources :categories
  resources :courses
  resources :assessments do
    resources :questions, except: [:show] do
      put :update_position
      resources :answers, only: [:destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :courses, only: [:show]
      resources :versions, only: [:show]
      resources :resources
      resources :course_sections, only: [:show]
      resources :roles, only: [] do
        member do
          get :versions
        end
      end
      resources :assessments, only: [:show]
      resources :user_courses, only: [:show] do
        resources :user_course_sections, controller: 'user_courses',
                                         action: 'sections', type: 'section'
        member do
          get :assessments
        end
        resources :user_course_assessments, only: [:show]
      end
      resources :chapters, only: [:show]
      resources :chapter_resources, controller: 'chapters',
                                    only: [:show], type: 'Resource'
      resources :user_course_assessments, only: [:create]
      resources :user_course_progresses, only: [:create, :show]
      resources :user_questions, only: [:create]
      resources :evaluation_questions, only: :create
    end
  end
  namespace :course_taking do
    resources :templates, only: :show
    get '/courses/:course_id/preview', to: 'templates#index', as: 'preview'
    get '/courses/:course_id', to: 'templates#index'
    get '/*path', to: 'templates#index'
  end
  match '*path', to: 'application#routing_error', via: :all
end

course_creation/app/models/course_creation/answer.rb
module CourseCreation
  # Course Model
  class Answer < ActiveRecord::Base
    belongs_to :question
    acts_as_list scope: :question
    mount_uploader :image, ImageUploader
    include CourseCreation::VersionValidator
    validate :version_published, on: :create, if: 'question.present?'
    before_destroy :version_editable
  end
end

course_creation/app/models/course_creation/assessment.rb
# course creation
module CourseCreation
  # Assessment module
  class Assessment < ActiveRecord::Base
    include CourseContent
    # Removing test and practise(Assessment as quiz type was only
    # supportes { test: 'Test', quiz: 'Quiz', practice: 'Practice' })
    TYPES = { quiz: 'Quiz' }
    PASSING_CRITERIA_YES = true
    PASSING_CRITERIA_NO = false
    ASSESSMENT = 'Assessment'
    belongs_to :course_section
    has_many :questions, dependent: :destroy
    validates :name, presence: true
    validates_length_of :name, maximum: 50
    validates :assessment_type, presence: true
    validates :passing_percentage, inclusion: { in: 0..100, allow_nil: true,
                                                message: I18n.t(:percentage) }
    validates :no_of_displayed_questions, numericality: true, allow_nil: true
    include CourseCreation::VersionValidator
    validate :version_published, on: :create
    before_destroy :version_editable
    before_update :editable?

    def editable?
      return true if course_section.version.editable?
      if passing_criteria_changed? || assessment_type_changed? ||
         passing_percentage_changed? ||
         no_of_displayed_questions_changed?
        false
      else
        true
      end
    end

    def valid_assessment?
      questions.any? && (no_of_displayed_questions.to_i <= questions.count)
    end
  end
end

course_creation/app/models/course_creation/category.rb
module CourseCreation
  # Course Categories Model
  class Category < ActiveRecord::Base
    has_many :versions, dependent: :destroy
    validates :name,
              presence: { message: I18n.t(
                'course_creation.categories.blank_name_message') },
              uniqueness: { message: I18n.t(
                'course_creation.categories.duplicate_name_message') }
  end
end

course_creation/app/models/course_creation/center_column.rb
module CourseCreation
  # Slide Center column Content
  class CenterColumn < SlideContent; end
end

course_creation/app/models/course_creation/certificate.rb
module CourseCreation
  # Certificate model
  class Certificate < ActiveRecord::Base
    has_many :courses
    validates :title, presence: true
    COURSE_COMPLETE_STATUS = 2

    # Return array of courses objects asociated with certificate
    def associated_course_versions
      courses.includes(:versions)
    end

    # Return array of courses ids asociated with certificate
    def associated_course_ids
      course_ids
    end

    def update_certificate
      update_attributes(editable: false)
    end

    def certification_taken?
      associated_course_versions.map do |course|
        return true unless course.versions.first.editable
      end
      false
    end

    def user_certification_completed?(user_id)
      return false if course_ids.nil?
      user_course_ids = CourseCreation::CourseTaking::UserCourse.where(
        version_id: course_ids, user_id: user_id,
        course_status: COURSE_COMPLETE_STATUS).count
      user_course_ids == course_ids.count
    end
  end
end

course_creation/app/models/course_creation/course.rb
module CourseCreation
  # Course Model
  class Course < ActiveRecord::Base
    has_many :versions, dependent: :destroy
    belongs_to :categories
    belongs_to :certificate
    accepts_nested_attributes_for :versions
    validates :title, presence: { message: I18n.t(
                'course_creation.courses.blank_title_message') }, uniqueness: { message: I18n.t(
                'course_creation.courses.duplicate_title_message') }

    class << self
      def published_versions
        CourseCreation::Course.joins(
          :versions).where(course_creation_versions: { published: true })
      end
    end
  end
end

course_creation/app/models/course_creation/course_section.rb
module CourseCreation
  # Course Section model
  class CourseSection < ActiveRecord::Base
    belongs_to :version
    belongs_to :chapter, class_name: 'CourseSection', foreign_key: 'parent_id'
    has_many :contents, class_name: 'CourseSection', foreign_key: 'parent_id',
                        dependent: :destroy
    has_many :resources, dependent: :destroy

    has_one :content_resource, dependent: :destroy, class_name: 'Resource',
                               foreign_key: 'content_section_id'
    has_one :presentation, dependent: :destroy
    has_one :custom_content, dependent: :destroy
    has_one :interactive_slide, dependent: :destroy,
                                foreign_key: 'course_section_id'
    has_one :assessment, dependent: :destroy

    scope :chapters, -> { where(parent_id: nil) }

    validates :name, presence: true
    validates_length_of :name, maximum: 70
    CONTENT_TYPES = { presentation: 'presentation' }
    include RankedModel
    include ResourceCollection
    include CourseCreation::VersionValidator
    validate :version_editable, on: :create
    before_destroy :version_editable
    ranks :course_order,
          with_same: :version_id,
          scope: :chapters

    ranks :chapter_order,
          with_same: [:parent_id, :content]

    def section?
      parent_id.present? && !content
    end

    def sections
      contents.where(content: false)
    end

    def direct_contents
      contents.includes(:version, :content_resource, :presentation,
                        :interactive_slide, :custom_content, :assessment
                       ).where(content: true)
    end

    def section_content_present?
      content_resource.present? || validate_presentation? ||
        custom_content.present? || validate_assessment? ||
        valid_section? || interactive_slide.present?
    end

    def section_has_valid_contents?
      section_status = contents.any?
      if section_status
        contents.each do |sec|
          return false unless sec.section_content_present?
        end
      end
      section_status
    end

    def section_present?
      contents.each do |section|
        return false unless section.section_content_present?
      end
      true
    end

    def wrapped_content
      content_resource || presentation || custom_content || assessment ||
        interactive_slide
    end

    def validate_assessment?
      assessment.present? && assessment.valid_assessment?
    end

    def validate_presentation?
      presentation.present?
    end

    def valid_section?
      section? && section_has_valid_contents?
    end

    # course section cosider in course progress
    def valid_progress_content?
      content || is_assessment
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course.rb
module CourseCreation
  module CourseTaking
    # User course model
    class UserCourse < ActiveRecord::Base
      include CourseCreation::CoursePasser
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :version
      has_many :course_assessments, class_name: UserCourseAssessment,
                                    dependent: :destroy
      has_many :course_progresses, class_name: UserCourseProgress,
                                   dependent: :destroy
      has_many :user_questions, dependent: :destroy
      has_one :user_course_evaluation, dependent: :destroy
      COURSE_COMPLETE_STATUS = 2
      COURSE_INITIAL_STATUS = 1

      def self.preview_user_id
        CourseCreation.preview_user_id || CourseCreation.user_class.find_by(
          :email, CourseCreation.admin_email).id
      end

      def complete!
        update_attributes(course_status: COURSE_COMPLETE_STATUS)
      end

      def update_progress_percentage
        progress = progress_percentage.to_f + (version.contents_count * 100.0)
        update_attributes(progress_percentage: progress)
      end

      def update_version
        version.update_attributes(editable: false) if version.editable
      end

      def update_user_course_status
        update_attributes(course_status: COURSE_INITIAL_STATUS)
      end

      def update_course_content
        update_attributes(content_complete: true)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_assessment.rb
module CourseCreation
  module CourseTaking
    # User course assessment model
    class UserCourseAssessment < ActiveRecord::Base
      has_many :user_questions, dependent: :destroy, foreign_key: 'assessment_id'
      belongs_to :assessment, class_name: CourseCreation::Assessment
      belongs_to :user_course
      validates :assessment_id, :user_course_id, presence: true
      after_create :evaluate_assessment

      def evaluate_percentage
        questions = UserQuestion.where(
          'assessment_id = ? and user_course_id = ?',
          assessment_id, user_course_id)
        correct_questions = questions.where(passing_status: 1).count
        return 0 if questions.count == 0
        ((correct_questions.to_f / questions.count) * 100).to_i
      end

      def evaluate_assessment
        self.assessment_type = assessment.assessment_type
        self.assessment_percentage = evaluate_percentage
        self.status =
          assessment.passing_percentage <= assessment_percentage ? 1 : 0
        save
      end

      def delete_questions
        user_questions =
          CourseTaking::UserQuestion.where(
            'assessment_id = ? AND user_course_id = ?',
            assessment_id, user_course_id)
        user_questions.map(&:delete_answers)
        user_questions.destroy_all
      end

      def remove_assessment
        delete_questions
        CourseTaking::UserCourseAssessment.destroy(id)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_evaluation.rb
module CourseCreation
  module CourseTaking
    # User course evaluation model
    class UserCourseEvaluation < ActiveRecord::Base
      belongs_to :course_evaluation,
                 class_name: CourseCreation::EvaluationQuestion
      belongs_to :user_course
      has_many :evaluation_questions,
                class_name: CourseCreation::CourseTaking::UserCourseEvaluationQuestion,
                dependent: :destroy, foreign_key: 'user_course_evaluation_id'
      accepts_nested_attributes_for :evaluation_questions
      after_create do |user_course_evaluation|
        user_course_evaluation.user_course.complete!
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_evaluation_question.rb
module CourseCreation
  module CourseTaking
    # User course evaluation questions model
    class UserCourseEvaluationQuestion < ActiveRecord::Base
      belongs_to :user_course_evaluation,
                 class_name: CourseCreation::CourseTaking::UserCourseEvaluation
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_progress.rb
module CourseCreation
  module CourseTaking
    # User course progress model
    class UserCourseProgress < ActiveRecord::Base
      belongs_to :user_course
      belongs_to :section, class_name: CourseCreation::CourseSection,
                           foreign_key: :content_id
      before_save :validate_version
      after_save :update_course_progress
      validates :user_course_id, :content_id,
                :content_type, presence: true
      ATTEMPT = 1
      def save_status(status_code)
        self.status = status_code
      end

      def user_attempts
        self.attempt_to = attempt_to.nil? ? ATTEMPT : attempt_to + ATTEMPT
      end

      def self.update_course_progress(user_id, content_id, content_type,
                                      status)
        content_type =
          CourseSection.find(content_id).parent_id.nil? ? 'Chapter' : 'Section' if content_type.nil?
        progress = CourseTaking::UserCourseProgress.find_or_initialize_by(
          user_course_id: user_id,
          content_id: content_id,
          content_type: content_type
        )
        progress.status = status
        progress.save
      end

      def validate_version
        !user_course.version.editable
      end

      def update_course_progress
        return unless section.valid_progress_content? && valid_progress?
        user_course.update_progress_percentage
      end

      def valid_progress?
        const_status = CourseCreation::ApiStatuses::STATUS[2]
        (user_course.course_progresses.where(
          "content_id = #{content_id} AND status = #{const_status}"
        ).count == 1 &&
        status == const_status)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_descriptive.rb
module CourseCreation
  module CourseTaking
    # User descriptive model
    class UserDescriptive < ActiveRecord::Base
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :user_question
      belongs_to :answer
      delegate :position, to: :answer
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_objective_question_answer.rb
module CourseCreation
  module CourseTaking
    # User objective model
    class UserObjectiveQuestionAnswer < ActiveRecord::Base
      validates :answer_id, numericality: { only_integer: true }
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :user_question
      belongs_to :answer
      delegate :position, to: :answer
    end
  end
end

course_creation/app/models/course_creation/document.rb
module CourseCreation
  # Documenet Model
  class Document < Resource
    mount_uploader :file, DocumentUploader
    belongs_to :course_section
    belongs_to :content_section, class_name: 'CourseSection'
    validates :file, presence: true
    include CourseCreation::VersionValidator
    validate :version_published, on: :create
    before_destroy :version_editable
    include CourseContent
  end
end

course_creation/app/views/course_creation/slides/_column_1.html.haml
= f.fields_for :slide_contents, @slide_contents do |s|
  %li#left.single-column
    .content-uploaders.column-content-left{id: "btnBox_#{s.index}", class: "#{content_exist(@slide_contents[s.index])}"}
      = s.hidden_field :type, id: "contentType_#{s.index}"
      = s.hidden_field :orientation
      .custom-upload
        %input{type: 'button', value: 'Text', id: "addTextLeft_#{s.index}"}
      .custom-upload
        = s.file_field :file_url, id: "rightImageFileField_#{s.index}"
        .upload-file
          %span= localize('form.image_label')
      .custom-upload
        = s.file_field :video_url, id:"rightVideoFileField_#{s.index}"
        .upload-file
          %span= localize('form.video_label')
    .slide-name-wrap.hidden-area{id: "textField_#{s.index}"}
      = s.hidden_field :id , id: "col_#{s.index}"
      = s.text_area :content, id: "textContent_#{s.index}", class: 'tinymce'
      = link_to localize('form.cancel'), 'javascript:void(0)', id: "cancelTextLeft_#{s.index}", class: 'pull-right cancel'
      = link_to localize('form.save'), 'javascript:void(0)', id: "saveTextLeft_#{s.index}", class: 'pull-left save', data: { validationMessage: localize('form.text_validation_message')}
    .left-column-text{id: "contentLabel_#{s.index}", class: "#{text_content_exist(@slide_contents[s.index])}"}
      .left-column-text-content.editor-desc
        %div{id: "contentDiv_#{s.index}"}
          = column_content(@slide_contents[s.index]).html_safe
      = link_to('', 'javascript:void(0)', class: 'edit-content', id: "editColumn_#{s.index}")
      = link_to('', 'javascript:void(0)', class: 'remove-content', id: "removeColumn_#{s.index}")
    %div{id: "rightColumnImage_#{s.index}", class: "#{img_content_exist(@slide_contents[s.index])} content-img-wrap"}
      .presentation-img-wrap
        .img{{id: "imageDiv_#{s.index}"}}
          %img{src:"#{file_path(@slide_contents[s.index])}"}
        = link_to('', 'javascript:void(0)', class: 'remove-content', id: "delete_img_#{s.index}")
    %div{id:"rightColumnVideo_#{s.index}", class: "#{video_content_exist(@slide_contents[s.index])} content-video-wrap"}
      = hidden_field_tag "video_url_#{s.index}", "#{file_path(@slide_contents[s.index])}",class: 'video', data:{index: "#{s.index}"}
      %div{id: ['videoWrap', s.index]}
      = link_to('', 'javascript:void(0)', class: 'remove-content', id: "delete_video_#{s.index}")

course_creation/app/views/course_creation/slides/_column_2.html.haml
= f.fields_for :slide_contents, @slide_contents do |s|
  %li#right.two-column-slide
    .content-uploaders.column-content-right{id: "btnBox_#{s.index}", class: "#{content_exist(@slide_contents[s.index])}"}
      = s.hidden_field :type, id: "contentType_#{s.index}"
      = s.hidden_field :orientation
      .custom-upload
        %input{type:'button', value:localize('form.text_label'), id: "addTextLeft_#{s.index}"}
      .custom-upload
        = s.file_field :file_url, id: "rightImageFileField_#{s.index}"
        .upload-file
          %span= localize('form.image_label')
      .custom-upload
        = s.file_field :video_url, id: "rightVideoFileField_#{s.index}"
        .upload-file
          %span= localize('form.video_label')
    .slide-name-wrap.hidden-area{id: "textField_#{s.index}"}
      = s.hidden_field :id , id: "col_#{s.index}"
      = s.text_area :content, id: "textContent_#{s.index}", class: 'tinymce'
      = link_to localize('form.cancel'), 'javascript:void(0)', id: "cancelTextLeft_#{s.index}", class: 'pull-right cancel'
      = link_to localize('form.save'), 'javascript:void(0)', id: "saveTextLeft_#{s.index}", class: 'pull-left save', data: { validationMessage: localize('form.text_validation_message')}
    .right-column-text-save.hidden-area
    .right-column-text{id: "contentLabel_#{s.index}", class: "#{text_content_exist(@slide_contents[s.index])}"}
      .right-column-text-content.editor-desc
        %div{id: "contentDiv_#{s.index}"}
          = column_content(@slide_contents[s.index]).html_safe
      = link_to('', 'javascript:void(0)', class: 'edit-content', id: "editColumn_#{s.index}")
      = link_to('', 'javascript:void(0)', class: 'remove-content', id: "removeColumn_#{s.index}")
    .content-img-wrap{id: "rightColumnImage_#{s.index}", class: "#{img_content_exist(@slide_contents[s.index])}"}
      .presentation-img-wrap
        .img{{id: "imageDiv_#{s.index}"}}
          %img{src:"#{file_path(@slide_contents[s.index])}"}
        = link_to('', 'javascript:void(0)', class: 'remove-content', id: "delete_img_#{s.index}")
    %div{id:"rightColumnVideo_#{s.index}", class: "#{video_content_exist(@slide_contents[s.index])} content-video-wrap"}
      = hidden_field_tag "video_url_#{s.index}", "#{file_path(@slide_contents[s.index])}", class: 'video', data:{index: "#{s.index}"}
      %div{id: ['videoWrap', s.index]}
      = link_to('', 'javascript:void(0)', class: 'remove-content', id: "delete_video_#{s.index}")

course_creation/app/views/course_creation/slides/_form.html.haml
%div{class:'col-md-9'}
  = localize('form.title')
  .form-group
    = f.text_field :title, placeholder: localize('form.title_place')

course_creation/app/views/course_creation/slides/_slide_list.html.haml
%nav.slide-thum-wrapper
  %h4 Slides
  .nav-content
    %ul.slide-list.sortable{ data: { presentation_id: @presentation.id } }
      - @slides.each_with_index do |slide,index|
        %li.slide-box{ data: { slide_id: slide.id } }
          %i.slide-index
            = index + 1
          = link_to '', edit_version_course_section_presentation_slide_path(@version, @course_section, @presentation, slide), class: "show-slide slide-thumb column-#{slide.number_of_columns}-thumb #{active_slide_class(slide.id)}", data: {index: "#{localize('form.slide_title')} #{index + 1}"}
          = link_to '', version_course_section_presentation_slide_path(@version, @course_section, @presentation, slide), data: { method: :delete, confirm: t(:delete_message)}, class: 'delete-slide'
      %li
        %i.slide-index
        = link_to new_version_course_section_presentation_slide_path(@version, @course_section, @presentation), class: 'new-slide slide-thumb' do
          %i
          %span= localize('form.add_new_slide')

course_creation/app/views/course_creation/slides/edit.html.haml
%section.presentation-main-wrapper
  .custom-page-header.presentation-header
    .container
      .row
        .loader
        .col-md-5
          %h1= "#{localize('chapter_name')} : #{chapter_name}"
          %h4= "#{localize('section_name')} : #{@course_section.name}" if @chapter_name
        .col-md-5
          .prsentation-name.pull-right
            .presentation-label= @presentation.title
            = link_to '', 'javascript:void(0)', class: 'edit-presentation'
            .presentation-edit-controller
              .form-group
                = text_field_tag :title, @presentation.title, {id: 'ppt-edit-name', class: 'form-control'}
              = link_to localize('form.save'), 'javascript:void(0)', id: 'prt_save', class: 'save pull-left'
              = link_to localize('form.cancel'), 'javascript:void(0)', class: 'cancel'
            #error.error
              = localize(:title_err)
        .col-md-2
          .prsentation-name-update.pull-right
            = link_to localize('form.save_and_finish'), syllabus_version_path(@version), class: 'btn btn-lg btn-primary'
  .presentation-wrapper
    .slide-container
      .slide-content-wrapper
        = render('slide_list')
        .outer-wrapper
          = form_for @slide, url: version_course_section_presentation_slide_path, html: { method: :put } do |f|
            = f.hidden_field :id, id:'slide_id'
            = f.hidden_field :presentation_id, id: 'presentation_id'
            #ids{data:{version: @version.id, cs_id: @course_section.id, presentation_id: @presentation.id, id: @slide.id}}
            .show-slide-content
              .slide-heading
                %h4.pull-left
                = link_to localize('form.delete_slide_label'), version_course_section_presentation_slide_path(@version, @course_section, @presentation, @slide), data: { method: :delete, confirm: localize('form.delete_msg')}, class: 'pull-right'
              %span.slide-bold= localize('form.slide_setting_label')
              = render 'slide_settings', f:f
              .error-wrap
                #invalid_img.hidden-area
                  %span.error= localize(:invalid_image)
                #invalid_video.hidden-area
                  %span.error= localize(:invalid_video)
                #invalid_content.hidden-area
                  %span.error= localize(:empty_content)
                #wrong.hidden-area
                  %span.error= localize(:error)
                #error_apply_settings.hidden-area
                  .alert.alert-danger= localize(:error_apply_seetings)
              .success
                #apply_settings.hidden-area
                  .alert.alert-success= localize(:success_apply_settings)
              .slide-two-column.save-btn
                %span.slide-bold= localize('form.slide_content_label')
                .column-wrapper{style: "#{set_style}"}
                  .slide-title-panel
                    .column-heading
                      .slide-title.editor-desc{class: "#{slide_title_class}"}= slide_title || localize('form.title')
                      #titleEditorWrapper.hidden-area
                        = f.text_area :title, placeholder: localize('form.title_place'), class: 'title-tinymce'
                        = link_to localize('form.cancel'), 'javascript:void(0);', class: 'pull-right cancel'
                        = link_to localize('form.save'), 'javascript:void(0);', id: 'saveTitle', class: 'pull left save', data: { validationMessage: localize('form.content_validation_message')}
                      .title.hidden-area
                        .title-content
                        = link_to('', 'javascript:void(0)', class: 'edit-slide-title hidden-area')
                        = link_to('', 'javascript:void(0)', class: 'remove-title hidden-area title-controller')
                      .title-error.error.hidden-area
                      = link_to(localize('form.save'), 'javascript:void(0)', class: 'save-title title-controller')
                      = link_to(localize('form.cancel'), 'javascript:void(0)', class: 'delete-title title-controller')
                    %ul.column-content
                      = render "column_#{@slide.number_of_columns}", f:f
              .slide-button
                = link_to(localize('form.add_new_slide_label'), new_version_course_section_presentation_slide_path(@version, @course_section, @presentation), class: 'slide-btn')
                = link_to(localize('form.duplicate_slide_label'), slide_clone_version_course_section_presentation_slide_path(@version, @course_section,@presentation, @slide), method: 'post', class: 'slide-btn')
                = link_to localize(:cancel), syllabus_version_path(@version), class:'pull-right'

course_creation/app/views/course_creation/slides/new.html.haml
%section.presentation-wrapper
  .custom-page-header
    .container
      %h1= "#{localize('chapter_name')} : #{chapter_name}"
      %h4= "#{localize('section_name')} : #{@course_section.name}" if @chapter_name
  .container
    .slide-content-wrap.new-slide-wrap
      = form_for @slide, url: version_course_section_presentation_slides_path, html: { method: :post } do |f|
        .slide-content
          %h3.subheading= localize('form.select_layout')
          %ul.layout-type
            %li.one-column-layout
              = f.text_field :number_of_columns, value: 1, type: 'submit'
            %li.two-column-layout
              = f.text_field :number_of_columns, value: 2, type: 'submit'
          .clearfix
    .form-group
      = link_to localize('form.back'), edit_version_course_section_presentation_slide_path(@version, @course_section, @presentation, @presentation.slides.first)