course_creation/config/routes.rb
CourseCreation::Engine.routes.draw do
  resources :certificates, except: [:show]
  resources :versions do
    member do
      put :publish
      get :preview
      get :syllabus, action: :show, version_view: 'Syllabus'
    end
    resources :course_sections, except: [:index, :show] do
      resources :resources do
        put :update_details
      end
      resources :videos, controller: 'resources', type: 'Video' do
        get :content, on: :new, action: :new, content: true
      end
      resources :presentations do
        resources :slides do
          member do
            put :update_settings
            put :update_ppt_title
            put :delete_bg_img
            put :update_title
            put :update_contents
            delete :destroy_column
            post :slide_clone
            put :apply_seetings
          end
        end
      end
      resources :section_assessments, controller: :assessments, type: 'section', only: [:new]
      resources :assessments
      resources :custom_contents
      resources :documents, controller: 'resources', type: 'Document' do
        get :content, on: :new, action: :new, content: true
      end
      resources :interactive_slides do
        resources :interactive_slides_informations do
          member do
            put :delete_slide_image
          end
        end
        resources :text_slides, controller:
          'interactive_slides_informations', type: 'TextSlide'
        resources :image_slides, controller:
          'interactive_slides_informations', type: 'ImageSlide'
        resources :text_image_slides, controller:
          'interactive_slides_informations', type: 'TextImageSlide'
      end
    end
    resources :evaluation_questions, except: [:show, :new]
    resources :resources
    get :documents, controller: 'resources', action: :index, type: 'Document'
    get :videos, controller: 'resources', action: :index, type: 'Video'
    resources :quotes, controller: 'resources', type: 'Quote'
    resources :notes, controller: 'resources', type: 'Note'
  end
  resources :categories
  resources :courses
  resources :assessments do
    resources :questions, except: [:show] do
      put :update_position
      resources :answers, only: [:destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :courses, only: [:show]
      resources :versions, only: [:show]
      resources :resources
      resources :course_sections, only: [:show]
      resources :roles, only: [] do
        member do
          get :versions
        end
      end
      resources :assessments, only: [:show]
      resources :user_courses, only: [:show] do
        resources :user_course_sections, controller: 'user_courses',
                                         action: 'sections', type: 'section'
        member do
          get :assessments
        end
        resources :user_course_assessments, only: [:show]
      end
      resources :chapters, only: [:show]
      resources :chapter_resources, controller: 'chapters',
                                    only: [:show], type: 'Resource'
      resources :user_course_assessments, only: [:create]
      resources :user_course_progresses, only: [:create, :show]
      resources :user_questions, only: [:create]
      resources :evaluation_questions, only: :create
    end
  end
  namespace :course_taking do
    resources :templates, only: :show
    get '/courses/:course_id/preview', to: 'templates#index', as: 'preview'
    get '/courses/:course_id', to: 'templates#index'
    get '/*path', to: 'templates#index'
  end
  match '*path', to: 'application#routing_error', via: :all
end

course_creation/app/models/course_creation/answer.rb
module CourseCreation
  # Course Model
  class Answer < ActiveRecord::Base
    belongs_to :question
    acts_as_list scope: :question
    mount_uploader :image, ImageUploader
    include CourseCreation::VersionValidator
    validate :version_published, on: :create, if: 'question.present?'
    before_destroy :version_editable
  end
end

course_creation/app/models/course_creation/assessment.rb
# course creation
module CourseCreation
  # Assessment module
  class Assessment < ActiveRecord::Base
    include CourseContent
    # Removing test and practise(Assessment as quiz type was only
    # supportes { test: 'Test', quiz: 'Quiz', practice: 'Practice' })
    TYPES = { quiz: 'Quiz' }
    PASSING_CRITERIA_YES = true
    PASSING_CRITERIA_NO = false
    ASSESSMENT = 'Assessment'
    belongs_to :course_section
    has_many :questions, dependent: :destroy
    validates :name, presence: true
    validates_length_of :name, maximum: 50
    validates :assessment_type, presence: true
    validates :passing_percentage, inclusion: { in: 0..100, allow_nil: true,
                                                message: I18n.t(:percentage) }
    validates :no_of_displayed_questions, numericality: true, allow_nil: true
    include CourseCreation::VersionValidator
    validate :version_published, on: :create
    before_destroy :version_editable
    before_update :editable?

    def editable?
      return true if course_section.version.editable?
      if passing_criteria_changed? || assessment_type_changed? ||
         passing_percentage_changed? ||
         no_of_displayed_questions_changed?
        false
      else
        true
      end
    end

    def valid_assessment?
      questions.any? && (no_of_displayed_questions.to_i <= questions.count)
    end
  end
end

course_creation/app/models/course_creation/category.rb
module CourseCreation
  # Course Categories Model
  class Category < ActiveRecord::Base
    has_many :versions, dependent: :destroy
    validates :name,
              presence: { message: I18n.t(
                'course_creation.categories.blank_name_message') },
              uniqueness: { message: I18n.t(
                'course_creation.categories.duplicate_name_message') }
  end
end

course_creation/app/models/course_creation/center_column.rb
module CourseCreation
  # Slide Center column Content
  class CenterColumn < SlideContent; end
end

course_creation/app/models/course_creation/certificate.rb
module CourseCreation
  # Certificate model
  class Certificate < ActiveRecord::Base
    has_many :courses
    validates :title, presence: true
    COURSE_COMPLETE_STATUS = 2

    # Return array of courses objects asociated with certificate
    def associated_course_versions
      courses.includes(:versions)
    end

    # Return array of courses ids asociated with certificate
    def associated_course_ids
      course_ids
    end

    def update_certificate
      update_attributes(editable: false)
    end

    def certification_taken?
      associated_course_versions.map do |course|
        return true unless course.versions.first.editable
      end
      false
    end

    def user_certification_completed?(user_id)
      return false if course_ids.nil?
      user_course_ids = CourseCreation::CourseTaking::UserCourse.where(
        version_id: course_ids, user_id: user_id,
        course_status: COURSE_COMPLETE_STATUS).count
      user_course_ids == course_ids.count
    end
  end
end

course_creation/app/models/course_creation/course.rb
module CourseCreation
  # Course Model
  class Course < ActiveRecord::Base
    has_many :versions, dependent: :destroy
    belongs_to :categories
    belongs_to :certificate
    accepts_nested_attributes_for :versions
    validates :title, presence: { message: I18n.t(
                'course_creation.courses.blank_title_message') }, uniqueness: { message: I18n.t(
                'course_creation.courses.duplicate_title_message') }

    class << self
      def published_versions
        CourseCreation::Course.joins(
          :versions).where(course_creation_versions: { published: true })
      end
    end
  end
end

course_creation/app/models/course_creation/course_section.rb
module CourseCreation
  # Course Section model
  class CourseSection < ActiveRecord::Base
    belongs_to :version
    belongs_to :chapter, class_name: 'CourseSection', foreign_key: 'parent_id'
    has_many :contents, class_name: 'CourseSection', foreign_key: 'parent_id',
                        dependent: :destroy
    has_many :resources, dependent: :destroy

    has_one :content_resource, dependent: :destroy, class_name: 'Resource',
                               foreign_key: 'content_section_id'
    has_one :presentation, dependent: :destroy
    has_one :custom_content, dependent: :destroy
    has_one :interactive_slide, dependent: :destroy,
                                foreign_key: 'course_section_id'
    has_one :assessment, dependent: :destroy

    scope :chapters, -> { where(parent_id: nil) }

    validates :name, presence: true
    validates_length_of :name, maximum: 70
    CONTENT_TYPES = { presentation: 'presentation' }
    include RankedModel
    include ResourceCollection
    include CourseCreation::VersionValidator
    validate :version_editable, on: :create
    before_destroy :version_editable
    ranks :course_order,
          with_same: :version_id,
          scope: :chapters

    ranks :chapter_order,
          with_same: [:parent_id, :content]

    def section?
      parent_id.present? && !content
    end

    def sections
      contents.where(content: false)
    end

    def direct_contents
      contents.includes(:version, :content_resource, :presentation,
                        :interactive_slide, :custom_content, :assessment
                       ).where(content: true)
    end

    def section_content_present?
      content_resource.present? || validate_presentation? ||
        custom_content.present? || validate_assessment? ||
        valid_section? || interactive_slide.present?
    end

    def section_has_valid_contents?
      section_status = contents.any?
      if section_status
        contents.each do |sec|
          return false unless sec.section_content_present?
        end
      end
      section_status
    end

    def section_present?
      contents.each do |section|
        return false unless section.section_content_present?
      end
      true
    end

    def wrapped_content
      content_resource || presentation || custom_content || assessment ||
        interactive_slide
    end

    def validate_assessment?
      assessment.present? && assessment.valid_assessment?
    end

    def validate_presentation?
      presentation.present?
    end

    def valid_section?
      section? && section_has_valid_contents?
    end

    # course section cosider in course progress
    def valid_progress_content?
      content || is_assessment
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course.rb
module CourseCreation
  module CourseTaking
    # User course model
    class UserCourse < ActiveRecord::Base
      include CourseCreation::CoursePasser
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :version
      has_many :course_assessments, class_name: UserCourseAssessment,
                                    dependent: :destroy
      has_many :course_progresses, class_name: UserCourseProgress,
                                   dependent: :destroy
      has_many :user_questions, dependent: :destroy
      has_one :user_course_evaluation, dependent: :destroy
      COURSE_COMPLETE_STATUS = 2
      COURSE_INITIAL_STATUS = 1

      def self.preview_user_id
        CourseCreation.preview_user_id || CourseCreation.user_class.find_by(
          :email, CourseCreation.admin_email).id
      end

      def complete!
        update_attributes(course_status: COURSE_COMPLETE_STATUS)
      end

      def update_progress_percentage
        progress = progress_percentage.to_f + (version.contents_count * 100.0)
        update_attributes(progress_percentage: progress)
      end

      def update_version
        version.update_attributes(editable: false) if version.editable
      end

      def update_user_course_status
        update_attributes(course_status: COURSE_INITIAL_STATUS)
      end

      def update_course_content
        update_attributes(content_complete: true)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_assessment.rb
module CourseCreation
  module CourseTaking
    # User course assessment model
    class UserCourseAssessment < ActiveRecord::Base
      has_many :user_questions, dependent: :destroy, foreign_key: 'assessment_id'
      belongs_to :assessment, class_name: CourseCreation::Assessment
      belongs_to :user_course
      validates :assessment_id, :user_course_id, presence: true
      after_create :evaluate_assessment

      def evaluate_percentage
        questions = UserQuestion.where(
          'assessment_id = ? and user_course_id = ?',
          assessment_id, user_course_id)
        correct_questions = questions.where(passing_status: 1).count
        return 0 if questions.count == 0
        ((correct_questions.to_f / questions.count) * 100).to_i
      end

      def evaluate_assessment
        self.assessment_type = assessment.assessment_type
        self.assessment_percentage = evaluate_percentage
        self.status =
          assessment.passing_percentage <= assessment_percentage ? 1 : 0
        save
      end

      def delete_questions
        user_questions =
          CourseTaking::UserQuestion.where(
            'assessment_id = ? AND user_course_id = ?',
            assessment_id, user_course_id)
        user_questions.map(&:delete_answers)
        user_questions.destroy_all
      end

      def remove_assessment
        delete_questions
        CourseTaking::UserCourseAssessment.destroy(id)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_evaluation.rb
module CourseCreation
  module CourseTaking
    # User course evaluation model
    class UserCourseEvaluation < ActiveRecord::Base
      belongs_to :course_evaluation,
                 class_name: CourseCreation::EvaluationQuestion
      belongs_to :user_course
      has_many :evaluation_questions,
                class_name: CourseCreation::CourseTaking::UserCourseEvaluationQuestion,
                dependent: :destroy, foreign_key: 'user_course_evaluation_id'
      accepts_nested_attributes_for :evaluation_questions
      after_create do |user_course_evaluation|
        user_course_evaluation.user_course.complete!
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_evaluation_question.rb
module CourseCreation
  module CourseTaking
    # User course evaluation questions model
    class UserCourseEvaluationQuestion < ActiveRecord::Base
      belongs_to :user_course_evaluation,
                 class_name: CourseCreation::CourseTaking::UserCourseEvaluation
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_course_progress.rb
module CourseCreation
  module CourseTaking
    # User course progress model
    class UserCourseProgress < ActiveRecord::Base
      belongs_to :user_course
      belongs_to :section, class_name: CourseCreation::CourseSection,
                           foreign_key: :content_id
      before_save :validate_version
      after_save :update_course_progress
      validates :user_course_id, :content_id,
                :content_type, presence: true
      ATTEMPT = 1
      def save_status(status_code)
        self.status = status_code
      end

      def user_attempts
        self.attempt_to = attempt_to.nil? ? ATTEMPT : attempt_to + ATTEMPT
      end

      def self.update_course_progress(user_id, content_id, content_type,
                                      status)
        content_type =
          CourseSection.find(content_id).parent_id.nil? ? 'Chapter' : 'Section' if content_type.nil?
        progress = CourseTaking::UserCourseProgress.find_or_initialize_by(
          user_course_id: user_id,
          content_id: content_id,
          content_type: content_type
        )
        progress.status = status
        progress.save
      end

      def validate_version
        !user_course.version.editable
      end

      def update_course_progress
        return unless section.valid_progress_content? && valid_progress?
        user_course.update_progress_percentage
      end

      def valid_progress?
        const_status = CourseCreation::ApiStatuses::STATUS[2]
        (user_course.course_progresses.where(
          "content_id = #{content_id} AND status = #{const_status}"
        ).count == 1 &&
        status == const_status)
      end
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_descriptive.rb
module CourseCreation
  module CourseTaking
    # User descriptive model
    class UserDescriptive < ActiveRecord::Base
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :user_question
      belongs_to :answer
      delegate :position, to: :answer
    end
  end
end

course_creation/app/models/course_creation/course_taking/user_objective_question_answer.rb
module CourseCreation
  module CourseTaking
    # User objective model
    class UserObjectiveQuestionAnswer < ActiveRecord::Base
      validates :answer_id, numericality: { only_integer: true }
      belongs_to :user, class_name: CourseCreation.user_class
      belongs_to :user_question
      belongs_to :answer
      delegate :position, to: :answer
    end
  end
end

course_creation/app/models/course_creation/document.rb
module CourseCreation
  # Documenet Model
  class Document < Resource
    mount_uploader :file, DocumentUploader
    belongs_to :course_section
    belongs_to :content_section, class_name: 'CourseSection'
    validates :file, presence: true
    include CourseCreation::VersionValidator
    validate :version_published, on: :create
    before_destroy :version_editable
    include CourseContent
  end
end

course_creation/app/views/course_creation/resources/_content_form.html.haml
.edit-course-section.add-pdf-wrap.content-form
  = form_for [version, section, resource], html: {class:'well document-content'}, remote: true do |f|
    .notice.error
    .form-field
      = f.label(localize(:field_title), class: 'chapter-name mandatory')
      .form-group
        = f.text_field :title, class: 'form-control', maxlength: '50', placeholder: localize("field_title_place_#{@type.downcase}")
    .form-field
      = description_label
      .form-group
        = f.send(description_field, :description, placeholder: localize("description_place_#{@type.downcase}"), class: 'form-control')
        = f.hidden_field :version_id, value: version.id
        = f.hidden_field :course_section_id, value: section.id
        = hidden_field_tag(:syllabus, true)
    .form-field
      .form-group
        = f.file_field :file
        .note= localize("add_#{@type.downcase}_note")
    .clearfix
    .edit-btn-group
      = f.submit localize('submit'), class: 'cs-edit-submit btn btn-primary submit-resource', data: { name_message: localize('empty_title'), invalid_content: localize('invalid_content'), upload_mp4: localize('blank_content_message'), upload_pdf: localize('blank_pdf_message')}
      = link_to localize('cancel'), 'javascript:void(0)', class: 'cancel-edit'
= chapter_tag(section)

course_creation/app/views/course_creation/resources/_form.html.haml
%section.add-note
  .custom-page-header
    %h1= @type
  = form_for [@version, @resource] do |f|
    .field.text-resource-form.clearfix
      .form-group
        - if @type == 'Note'
          = f.label('', localize(:add_note_title), class: 'mandatory')
          = f.text_field :title, placeholder: localize(:title_place), class: 'form-control required', data: { message: @resource.errors[:title].first }, maxlength: '50'
        - if @resource.errors.any?
          #error_explanation.error
            %span
              - @resource.errors.full_messages.each do |message|
                = message
      .form-group.full-form-group
        = f.label('', localize(:add_note_content), class: 'mandatory')
        = f.text_area :content, class: 'tinymce'
        %span.description-error.error
        = f.hidden_field :version_id, value: @version.id
        = f.hidden_field :type
      - if @type == 'Quote'
        .form-group
          = f.label('', localize(:add_quote_author), class: 'mandatory')
          = f.text_field :title, placeholder: localize(:author_place), class: 'form-control required', maxlength: '50'
      .form-group
        .actions
          = f.submit(localize(:save), class: 'btn btn-primary submit-resource', data: { message: localize('empty_field_message'), type: @type })
          = link_to localize(:cancel_btn), text_resources_path

course_creation/app/views/course_creation/resources/_text_resources.html.haml
%section.add-resources-wrap
  .custom-page-header
    %h1= @type
  #resource-info{ data: { version_id: @version.id, type: @type } }
  .add-quote-wrap
    .resource-lisiting
      .resource-list
        %ul.chapter.content-listing
          - version.resources_order(@type).each do |resource|
            %li.resource{ data: { resource_id: resource.id } }
              .version-title
                %span= resource.title
                .version-action-wrap
                  = link_to '', send("edit_version_#{resource_type}_path", version.id, resource.id), class: 'resource-link edit-btn'
                  = link_to '', [version, resource], method: :delete, class: 'resource-link delete-btn', data: { confirm: t('delete_message') }
    = link_to content_tag(:span, "Add #{resource_type}"), send("new_version_#{resource_type}_path", version), class: 'add-new-chapter-btn'

course_creation/app/views/course_creation/resources/_upload_resources.html.haml
%section.add-note
  .custom-page-header
    %h1= localize(:resourses_title)
    %h4
      %span= localize(:course_name)
      %span /
      %span= localize(:Course_resources)
      %span /
      %span= resource_title
  #resource-info{ data: { version_id: @version.id, type: @type } }
  %ul.resource-lisiting
    - chapters.each do |c|
      %li.chapter{data: {chapter_id: c.id, version_id: c.version.id}}
        = div_for(c, class: 'resource-chapter') do
          .add-chapter-wrap
            .chapter-name-wrap
              = c.name
              .cs-button.add-btn-syllabus
                = link_to localize("add_new_#{resource_type}"), send("new_version_course_section_#{resource_type}_path", c.version.id, c.id), class: 'resource-link btn btn-default btn-xs'
        %ul.resource-list.sortable.content-listing
          - c.resources_order(resource_type).each do |s|
            %li.resource{data: {resource_id: s.id}}
              = div_for(s, class: 'resource-container') do
                = s.title
                \:
                = link_to s.file.sanitized_file.original_filename, s.file.url
                .action-wrap
                  = link_to '', send("edit_version_course_section_#{resource_type}_path", c.version.id, c.id, s.id), class: 'resource-link edit-btn'
                  = link_to '', [c.version, c, s], method: :delete, class: 'resource-link delete-btn', data: {confirm: t('delete_message')}

course_creation/app/views/course_creation/resources/edit.html.haml
-if %w(Quote Note).include? params[:type]
  =render 'form'
-else
  %section.add-note
    .custom-page-header
      %h1= localize(:title)
    .loader
    .videos.video-detail-wrapper
      = form_for [@version, @section, @resource] do |f|
        - if @resource.errors.any?
          #error_explanation.error
            %span
              = pluralize(@resource.errors.count, 'error')
              = localize('error_message')
            %ul
              - @resource.errors.full_messages.each do |message|
                %li= message
        .form-group.well
          = f.file_field :file
          .note
            = supported_formats_msg(@resource.type)
        .well
          .form-group.default-img-wrapper
            = label_tag resource_file_name(@resource.file.path)
          .form-group
            = f.label('', localize(:title_lb), class: 'mandatory')
            = f.text_field :title, {class: 'form-control required', id: "title-#{@resource.id}", maxlength: '50'}
          .form-group.full-form-group
            = f.send(description_field, :description, class: 'required no-mce form-control', id: "description-#{@resource.id}")
            = f.hidden_field :course_section_id
            = f.hidden_field :type
            = f.hidden_field :version_id, value: @version.id
            = link_to localize(:delete_btn), [@version, @section, @resource], method: :delete, class: 'remove-video', data: {confirm: localize('delete_message')}
        .form-group
          .actions
            = f.submit(localize(:save), class: 'btn btn-primary')
            = link_to(localize(:cancel_btn), 'javascript:void(0)')

course_creation/app/views/course_creation/resources/index.html.haml
.chapter-container
  #course_content= resource_partial(@chapters, @version)

course_creation/app/views/course_creation/resources/new.html.haml
-if %w(Quote Note).include? params[:type]
  =render 'form'
-else
  .loader
  %section
    .custom-page-header
      %h1= @section.name
      %h4= heading_name(@resource.type)
    .error
      #invalidPdf.hidden-area
        .error= localize(:invalid_pdf)
      #invalidVideo.hidden-area
        .error= localize(:invalid_video)
      #error.hidden-area.alert.alert-danger= localize(:error)
      #error_msg.hidden-area.alert.alert-danger
    = form_for @resource, url: create_form_action(@resource.type), html: {id: 'resource_form', class: 'well video-load-wrapper', method: :post, data: {type: @resource.type }} do |f|
      - if @resource.errors.any?
        #error_explanation.error
          %span
            = pluralize(@resource.errors.count, 'error')
            = localize('error_message')
          %ul
            - @resource.errors.full_messages.each do |message|
              %li= message

      .control-group
        = f.file_field :file, name:file_field_name(@resource.type), id: 'resource_file', multiple: true
        = f.hidden_field :title
        = f.hidden_field :course_section_id, value: @section.id
        = f.hidden_field :version_id, value: @version.id
        = f.hidden_field :description
        = f.hidden_field :type
      .note
        = supported_formats_msg(@resource.type)
    .videos
    %script{id: 'resource_id', type: 'text/html'}
      .video-detail-wrapper{id:"resource_{{count}}", data:{index: "{{count}}"}}
        %form{id: 'file-upload'}
          .default-img-wrapper
            ="{{name}}"
          .form-group
            %label.mandatory
              = localize(:field_title)
            =text_field_tag :title,'', maxlength: '50', class: 'form-control'
            .error
              #emptyTitle.hidden-area= localize(:empty_title)
          .form-group
            =description_label
            =description_tag
          =link_to(localize(:delete_btn), 'javascript:void(0)', class: 'remove-video', data: { resource: "{{count}}"})
    .actions.hidden-area
      =link_to(localize(:save_btn), 'javascript:void(0)', class: 'add-video-details btn btn-primary')
      = link_to(localize(:back_btn), syllabus_version_path(@version))